### ISSUE TITLE
10.13.6升级的问题

### ISSUE THREAD

**Issue by iPermanent** [MichaelVector/XPS15-9560-MacOS10.13.6#3]
之前淘宝花钱找人装了个10.13 然后一路升级到10.13.6，好奇的是这种方式安装好了的黑苹果可以直接覆盖安装升级么，有没有什么需要注意的坑

**Comment by MichaelVector** [comment]
升级的话小版本升级没问题的，大版本有些区别，主要就是驱动，只要能驱动，跨版本也没问题的

**Comment by MichaelVector** [comment]
其实不用花钱，网上大把同样机型的电脑，找好plist和驱动就行了

**Comment by iPermanent** [comment]
悲剧的是已经升级升挂了，也是XPS  不过是4K屏幕16G/512G的那款，在准备重新安装

**Comment by MichaelVector** [comment]
不管升不升级，保留EFI文件就行，升级只是对系统分区升级，只要变一下EFI就可以用，只不过说你的EFI文件不支持升级后的系统稳定进入而已，其实找一个最简版的EFI支持新系统的EFI可以进入安装界面的安装也可以

**Comment by MichaelVector** [comment]
我的系统是从10.13一路升到10.14的，因为用了TimeMachine，所以升级对我来说最安全保险，升级后只要修改下EFI就没问题的

**Comment by iPermanent** [comment]
已经重装好了，把我安装的过程分享一下：使用appstore的原版镜像制作DMG，然后使用白苹果下的clover挂载U盘efi分区，然后把你clover里面的东西往内部替换，但是替换以后还是开不了机，就用了另一个哥们的clover增量替换了一下，那个efi地址在https://github.com/jardenliu/XPS15-9560-Mojave  进安装界面了，安装完成以后，需要把EFI里的clover部分拷到硬盘ESP分区，这个时候，只能用你这个引导了，用那个哥们的efi只能引导安装，不能引导开机，用你的可以引导开机，驱动完美，我的是4K触摸屏的，除了读卡器和独显以后都OK了，感谢提供efi
<img width="586" alt="wx20180930-101416 2x" src="https://user-images.githubusercontent.com/1712759/46252324-043e4e80-c49a-11e8-9f85-ab4988869e67.png">

**Comment by MichaelVector** [comment]
不客气哈，恭喜成功黑苹果
