### ISSUE TITLE
关于如何挂载ESP分区的问题

### ISSUE THREAD

**Issue by iPermanent** [MichaelVector/XPS15-9560-MacOS10.13.6#4]
请问下该如何挂载ESP分区编辑EFI文件呢，我是直接写在windows分区里的EFI，但是没法编辑替换驱动，所以安装的时候一直出现禁止符，使用的黑果小兵提供的懒人版盘

**Comment by MichaelVector** [comment]
用disk genius,可以在win下打开EFI分区进行修改编写
