### ISSUE TITLE
自动重启问题

### ISSUE THREAD

**Issue by houbo0601** [MichaelVector/XPS15-9560-MacOS10.13.6#5]
处理器是i5的款,其他配置和你的一模一样，安装完，使用正常，就是隔五到十分钟就会自动重启

**Comment by MichaelVector** [comment]
先要明白哈，clover只是用来引导进入系统的，包括驱动和配置，是为了驱动硬件正常工作，能进入系统如果查看大部分驱动都正常使用，说明问题不在clover，如果不定时关机，请检查下bios或者系统硬件或者安装包是否原生

**Comment by MichaelVector** [comment]
能进入系统驱动没问题就是问题不在clover上，是不安装啥软件造成的问题

**Comment by houbo0601** [comment]
好的，明白了，多谢，我检查一下bios

**Comment by MichaelVector** [comment]
也有可能是自己安装的软件，建议安装完什么软件都不要装试试看下还是否有问题

**Comment by houbo0601** [comment]
安装包用的黑果小兵的正是版

**Comment by MichaelVector** [comment]
我也用的是这个，没有出现过你的那个问题，是不软件造成的原因或是修改过睡眠问题

**Comment by houbo0601** [comment]
你的BIOS设置改了哪些？我用的是 jardenliu的https://github.com/jardenliu/XPS15-9560-Mojave/blob/master/BIOS.md 的bios设置

**Comment by MichaelVector** [comment]
都一样的，差不多，不一定要一模一样，看需求，你还是自动重启的问题吗？

**Comment by houbo0601** [comment]
重新把bios检查了一遍，换了你这个最新的clover包，好了，今天再观察观察！
